title: Karthik Dantu
email: kdantu@buffalo.edu
description: Homepage for Karthik Dantu, Associate Professor of Computer Science and Engineering at the University at Buffalo.
url: https://dkkarthik.github.io
baseurl: ""
lang: en
markdown: kramdown
include:
  - _pages
exclude:
  - bin
  - node_modules
  - vendor
  - prototype/index.html
  - prototype/styles.css
